# Generated by Django 3.1.2 on 2020-11-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='user_being_followed',
        ),
        migrations.AddField(
            model_name='follower',
            name='user_follower',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='users_being_followed', to='network.user'),
            preserve_default=False,
        ),
    ]
